/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import modelo.ModeloElectrolisis;
import modelo.ParametroSimulado;
import modelo.ResultadoSimulado;
import javax.swing.JOptionPane;
import presentacion.GraficoEficienciaPanel;

/**
 *
 * @author vctor
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private GraficoEficienciaPanel graficoEficiencia;   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        graficoEficiencia = new GraficoEficienciaPanel();
        graficoEficiencia.setPreferredSize(new java.awt.Dimension(350, 250));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(graficoEficiencia, java.awt.BorderLayout.CENTER);
        
        cargarValoresPorDefecto();
    
    }
    private void cargarValoresPorDefecto() {
        ParametroSimulado defaultParams = new ParametroSimulado();
        txt_eficiencia.setText(String.valueOf(defaultParams.getEficiencia()));
        txt_temperatura.setText(String.valueOf(defaultParams.getTemperatura()));
        txt_factorCO2.setText(String.valueOf(defaultParams.getFactorCO2()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_corriente = new javax.swing.JTextField();
        txt_voltaje = new javax.swing.JTextField();
        txt_tiempo = new javax.swing.JTextField();
        txt_eficiencia = new javax.swing.JTextField();
        txt_temperatura = new javax.swing.JTextField();
        txt_factorCO2 = new javax.swing.JTextField();
        btn_simular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Simulación Interactiva de Hidrógeno Verde con Programación Orientada a Objetos y Ciencias Básicas");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Corriente:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Voltaje:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tiempo:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Eficiencia:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Temperatura:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Factor CO2:");

        txt_corriente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_corriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_corrienteActionPerformed(evt);
            }
        });

        txt_voltaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_tiempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tiempoActionPerformed(evt);
            }
        });

        txt_eficiencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_temperatura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_temperaturaActionPerformed(evt);
            }
        });

        txt_factorCO2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_factorCO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_factorCO2ActionPerformed(evt);
            }
        });

        btn_simular.setText("Simular");
        btn_simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simularActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_simular)
                .addGap(149, 149, 149))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_temperatura)
                            .addComponent(txt_factorCO2)
                            .addComponent(txt_eficiencia)
                            .addComponent(txt_tiempo)
                            .addComponent(txt_voltaje)
                            .addComponent(txt_corriente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_corriente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_voltaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_eficiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_factorCO2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_simular)
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_corrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_corrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_corrienteActionPerformed

    private void txt_tiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tiempoActionPerformed

    private void txt_temperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_temperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_temperaturaActionPerformed

    private void txt_factorCO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_factorCO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_factorCO2ActionPerformed

    private void btn_simularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simularActionPerformed
      
        String s_corriente, s_voltaje, s_tiempo, s_eficiencia, s_temperatura, s_factorCO2, mensaje = "";;
        this.jTextArea1.setText("");
        try {
            s_corriente = this.txt_corriente.getText().trim();
            s_voltaje = this.txt_voltaje.getText().trim();
            s_tiempo = this.txt_tiempo.getText().trim();
            s_eficiencia = this.txt_eficiencia.getText().trim();
            s_temperatura = this.txt_temperatura.getText().trim();
            s_factorCO2 = this.txt_factorCO2.getText().trim();
            
            if (s_corriente.isEmpty() || s_voltaje.isEmpty() || s_tiempo.isEmpty() || 
                s_eficiencia.isEmpty() || s_temperatura.isEmpty() || s_factorCO2.isEmpty()) {
                mensaje = "ERROR: Complete todos los campos de entrada para la simulación.";
                
            } else {
                double corriente = Double.parseDouble(s_corriente);
                double voltaje = Double.parseDouble(s_voltaje);
                double tiempo = Double.parseDouble(s_tiempo);
                double eficiencia = Double.parseDouble(s_eficiencia);
                double temperatura = Double.parseDouble(s_temperatura);
                double factorCO2 = Double.parseDouble(s_factorCO2);
                if (corriente < 0 || tiempo < 0 || voltaje < 0 || eficiencia < 0 || temperatura < 0) {
                     mensaje = "ERROR: Todos los parámetros deben ser valores positivos o cero.";
                } else {

                    ParametroSimulado parametros = new ParametroSimulado(corriente, tiempo,  voltaje,  eficiencia, temperatura, factorCO2);
                    ModeloElectrolisis modelo = new ModeloElectrolisis();
                    ResultadoSimulado resultados = modelo.simular(parametros); 
                    graficoEficiencia.añadirDato(voltaje, resultados.getEficiencia_energetica());
                    jPanel2.repaint();
                    this.jTextArea1.append("Resultados de la Simulación\n");
                    this.jTextArea1.append(resultados.mostrar_datosCadena());                    
                    mensaje = "Simulación ejecutada correctamente.";
                }
            }
            
        } catch(NumberFormatException ex) {
            mensaje = "ERROR: Valores numéricos inválidos. Revise que los campos contengan solo números.";
        } finally {
            JOptionPane.showMessageDialog(rootPane, mensaje);
        }
    
    }//GEN-LAST:event_btn_simularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_simular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txt_corriente;
    private javax.swing.JTextField txt_eficiencia;
    private javax.swing.JTextField txt_factorCO2;
    private javax.swing.JTextField txt_temperatura;
    private javax.swing.JTextField txt_tiempo;
    private javax.swing.JTextField txt_voltaje;
    // End of variables declaration//GEN-END:variables
}
